// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package da

import (
	"database/sql"
	"time"
)

type Product struct {
	ID        int64        `json:"id"`
	Name      string       `json:"name"`
	CreatedAt sql.NullTime `json:"created_at"`
	UpdatedAt time.Time    `json:"updated_at"`
}
