// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package da

import (
	"context"
)

type Querier interface {
	CreateProduct(ctx context.Context, name string) (int64, error)
	GetProducts(ctx context.Context) ([]*Product, error)
}

var _ Querier = (*Queries)(nil)
