// Package ports provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen/v2 version v2.0.0 DO NOT EDIT.
package ports

import (
	"github.com/gofiber/fiber/v2"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Get Products
	// (GET /app/products)
	GetProducts(c *fiber.Ctx) error
	// Create Product
	// (POST /app/products)
	CreateProduct(c *fiber.Ctx) error
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

type MiddlewareFunc fiber.Handler

// GetProducts operation middleware
func (siw *ServerInterfaceWrapper) GetProducts(c *fiber.Ctx) error {

	return siw.Handler.GetProducts(c)
}

// CreateProduct operation middleware
func (siw *ServerInterfaceWrapper) CreateProduct(c *fiber.Ctx) error {

	return siw.Handler.CreateProduct(c)
}

// FiberServerOptions provides options for the Fiber server.
type FiberServerOptions struct {
	BaseURL     string
	Middlewares []MiddlewareFunc
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router fiber.Router, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, FiberServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router fiber.Router, si ServerInterface, options FiberServerOptions) {
	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	for _, m := range options.Middlewares {
		router.Use(m)
	}

	router.Get(options.BaseURL+"/app/products", wrapper.GetProducts)

	router.Post(options.BaseURL+"/app/products", wrapper.CreateProduct)

}
