openapi: 3.0.3
info:
  title: Purchasing
  description: Purchasing
  version: 1.0.0
servers:
  - url: 'https://localhost:8080/api/v1'
paths:
  /app/products:
    post:
      operationId: CreateProduct
      summary: Create Product
      responses:
        '201':
          description: Successful
    get:
      operationId: GetProducts
      summary: Get Products
      responses:
        '200':
          description: Successful